homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.6757775
  longitude: -71.08830859
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include_dir_merge_named customize
  # Packages file
  packages: !include_dir_named packages

python_script:

# Enables configuration UI
config:

ios:

zone:
  name: Home
  latitude: 41.6757775
  longitude: -71.08830859
  radius: 100  
    
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-mini-media-player.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-mini-media-player_es5.html
    - /local/custom_ui/state-card-tiles_es5.html
#  javascript_version: es5
    
camera:
  - platform: generic
    name: Driveway
    still_image_url: http://192.168.5.153/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=4f5df5e6&user=admin&password=Comein802!
  - platform: generic
    name: Backyard
    still_image_url: http://192.168.1.152/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=4f5df5e6&user=admin&password=Comein802!    
  - platform: generic
    name: Radar
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BOX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=1&rand=25281821&lat=0&lon=0&label=you
  
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: worldclock
    time_zone: America/New_York  
    
#  - platform: mqtt
#    name: "Zanzito Battery"
#    state_topic: "zanzito/mattsphone/battery_level"
#    qos: 0
#    unit_of_measurement: "%"   
 
  - platform: yr  
  
  - platform: nzbget
    host: 192.168.2.13
    username: nzbget
    password: !secret http_password
    monitored_variables:
      - download_paused
      - download_rate
      - post_paused
      - uptime
      - article_cache
      - remaining_size
  - platform: coinmarketcap
    currency: Ripple
  - platform: coinmarketcap
    currency: ICON
  - platform: coinmarketcap
    currency: Request-Network    
  - platform: coinmarketcap
    currency: vechain    
#  - platform: workday
#    country: US
#    workdays: [ mon, tue, wed, thu, fri ]
      
http:
  # Secrets are defined in the file secrets.yaml
   api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
   base_url: ha.maudette.com
   use_x_forwarded_for: True

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:
  
zwave:
  usb_path: /dev/ttyUSB0
  network_key: "0x72, 0x8C, 0xD5, 0xFA, 0xF5, 0x9B, 0x11, 0x0E, 0xCA, 0x2D, 0x59, 0x0B, 0xBE, 0xD2, 0x50, 0x3B"
  debug: true
  
zha:
  usb_path: /dev/ttyUSB1
  database_path: /srv/homeassistant3.6/lib/python3.6/site-packages/zigby/zigbee.db

# Text to speech
tts:
  - platform: google
  
#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: http://192.168.1.17:3218

ifttt:
  key: !secret ifttt_key
  
google_assistant:
  project_id: hass-189219
  client_id: aG8kHgC3fAP332uHYaZnShGQdvLWj2fSXqsmbZe7uVWTwQQ6XsUY8epuRCdxawbuUjBtFlVFAmkNrcFW
  access_token: 000
  agent_user_id: Matt
  api_key: !secret google_api_key
  exposed_domains:
    - switch
    - light
    - group  
    - media_player
    - script
    - climate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml